# Generated by Django 5.2.4 on 2025-08-04 20:13

import django.db.models.deletion
import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('num_days', models.PositiveIntegerField()),
                ('trip_code', models.CharField(default=trips.models.generate_trip_code, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('food', models.TextField(blank=True, help_text='List food or resturants you want to try')),
                ('shopping', models.TextField(blank=True, help_text='List shops or brands you want to go')),
                ('attractions', models.TextField(blank=True, help_text='List tourist spots or activities you want to visit and do')),
                ('beauty', models.TextField(blank=True, help_text='List beauty-related places you want to go or do')),
                ('additional_notes', models.TextField(blank=True, help_text='Any special request or things you would like to state')),
                ('budget', models.PositiveIntegerField(help_text='Enter your estimated budget (e.g. 500 for SGD500)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trips.trip')),
            ],
        ),
    ]
